import {  } from "stdlib/arraylist.zs"
let glist = newList<number>(4)
glist = listPush<number>(glist, 10, 4)
glist = listPush<number>(glist, 20, 4)
glist = listPush<number>(glist, 30, 4)
printNumber(listGet<number>(glist, 0))
printNumber(listGet<number>(glist, 1))
printNumber(listGet<number>(glist, 2))
printNumber(glist.len)
listFree<number>(glist, 4)
