package org.chisa.intellij.psi

object ChisaElementTypes {
    @JvmField val VAR_DECLARATION = ChisaElementType("VAR_DECLARATION")
    @JvmField val FN_DECLARATION = ChisaElementType("FN_DECLARATION")
    @JvmField val STRUCT_DECLARATION = ChisaElementType("STRUCT_DECLARATION")
    @JvmField val ENUM_DECLARATION = ChisaElementType("ENUM_DECLARATION")
    @JvmField val ENUM_VARIANT = ChisaElementType("ENUM_VARIANT")
    @JvmField val STRUCT_FIELD = ChisaElementType("STRUCT_FIELD")
    @JvmField val PARAMETER = ChisaElementType("PARAMETER")
    @JvmField val PARAMETER_LIST = ChisaElementType("PARAMETER_LIST")
    @JvmField val BLOCK = ChisaElementType("BLOCK")
    @JvmField val IF_STATEMENT = ChisaElementType("IF_STATEMENT")
    @JvmField val WHILE_STATEMENT = ChisaElementType("WHILE_STATEMENT")
    @JvmField val FOR_STATEMENT = ChisaElementType("FOR_STATEMENT")
    @JvmField val REFERENCE_EXPRESSION = ChisaElementType("REFERENCE_EXPRESSION")
    @JvmField val TYPE_REFERENCE = ChisaElementType("TYPE_REFERENCE")
    @JvmField val IMPORT_STATEMENT = ChisaElementType("IMPORT_STATEMENT")
    @JvmField val EXPORT_FROM_STATEMENT = ChisaElementType("EXPORT_FROM_STATEMENT")
    @JvmField val USE_STATEMENT = ChisaElementType("USE_STATEMENT")
    @JvmField val IMPORT_SYMBOL = ChisaElementType("IMPORT_SYMBOL")
    @JvmField val IMPORT_PATH = ChisaElementType("IMPORT_PATH")
    @JvmField val RETURN_STATEMENT = ChisaElementType("RETURN_STATEMENT")
    @JvmField val MATCH_EXPRESSION = ChisaElementType("MATCH_EXPRESSION")
    @JvmField val MATCH_ARM = ChisaElementType("MATCH_ARM")
    @JvmField val MATCH_BINDING = ChisaElementType("MATCH_BINDING")
    @JvmField val SCALAR_DECLARATION = ChisaElementType("SCALAR_DECLARATION")
    @JvmField val ARRAY_LITERAL = ChisaElementType("ARRAY_LITERAL")
    @JvmField val EXTENSION_FN_DECLARATION = ChisaElementType("EXTENSION_FN_DECLARATION")
    @JvmField val TYPE_ALIAS_DECLARATION = ChisaElementType("TYPE_ALIAS_DECLARATION")
    @JvmField val LAMBDA_EXPRESSION = ChisaElementType("LAMBDA_EXPRESSION")
    @JvmField val LAMBDA_PARAM = ChisaElementType("LAMBDA_PARAM")
    @JvmField val WHEN_EXPRESSION = ChisaElementType("WHEN_EXPRESSION")
    @JvmField val WHEN_ARM = ChisaElementType("WHEN_ARM")
    @JvmField val ASM_STATEMENT = ChisaElementType("ASM_STATEMENT")
    @JvmField val ASM_BINDING = ChisaElementType("ASM_BINDING")
    @JvmField val SAFE_NAVIGATION = ChisaElementType("SAFE_NAVIGATION")
    @JvmField val ERROR_PROPAGATION = ChisaElementType("ERROR_PROPAGATION")
    @JvmField val AT_TARGET = ChisaElementType("AT_TARGET")
}
